# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79f566c8b6f20bf2335057cac59182d1f1805efbaee12099fdfefb7cdfaa2b949ff177db814de962e62c71382ec7bf34bf4bfd592f67ed58070f850d29b99607

test:
  secret_key_base: de331e4cb91214be6c5ed94af25e43afc70ad541181e8bd9cb3d6137797543b3edbf1e9716b10eee2b5358c9ad3312a9246b4864149640963364bdc5d417bf5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
